force-app/main/default/objects/Country__c/Country__c.object-meta.xml
<CustomObject>
    <label>Country</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Countries</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Country__c/fields/Alpha_2_Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha_2_Code__c</fullName>
    <externalId>true</externalId>
    <label>Alpha-2 Code</label>
    <length>2</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Country_Capital__c.field-meta.xml
<CustomField>
    <fullName>Country_Capital__c</fullName>
    <label>Country Capital</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Country_Region__c.field-meta.xml
<CustomField>
    <fullName>Country_Region__c</fullName>
    <label>Country Region</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadTriggerHandler.cls
/**
 * @description       : 
 * @author            : Santiago Endre
 * @group             : 
 * @last modified on  : 06-05-2026
 * @last modified by  : Santiago Endre
**/
public with sharing class LeadTriggerHandler {

    public static void processRecords() {
        if (Trigger.isBefore) {
            Map<String,Country__c> countriesByCode = new Map<String,Country__c>();
            for (Country__c c : [SELECT Alpha_2_Code__c, Capital__c, Region__c FROM Country__c]) {
                countriesByCode.put(c.Alpha_2_Code__c, c);
            }

            for (Lead l : (List<Lead>)Trigger.new) {
                String countryCode = l.CountryCode;
                if (Trigger.isInsert || Trigger.isUpdate) {
                    if (countryCode != null && countriesByCode.containsKey(countryCode)) {
                        Country__c c = countriesByCode.get(countryCode);
                        l.Country_Capital__c = c.Capital__c;
                        l.Country_Region__c = c.Region__c;
                    }
                }
            }
        }
    }
}